export type City = {
  id: string
  label: string
}

/** 89 administrative centers of Russian federal subjects */
export const CITIES: City[] = [
  { id: 'moscow', label: 'Москва' },
  { id: 'saint-petersburg', label: 'Санкт-Петербург' },
  { id: 'sevastopol', label: 'Севастополь' },
  { id: 'simferopol', label: 'Симферополь' },
  { id: 'maikop', label: 'Майкоп' },
  { id: 'gorno-altaysk', label: 'Горно-Алтайск' },
  { id: 'ufa', label: 'Уфа' },
  { id: 'ulan-ude', label: 'Улан-Удэ' },
  { id: 'makhachkala', label: 'Махачкала' },
  { id: 'magas', label: 'Магас' },
  { id: 'nalchik', label: 'Нальчик' },
  { id: 'elista', label: 'Элиста' },
  { id: 'cherkessk', label: 'Черкесск' },
  { id: 'petrozavodsk', label: 'Петрозаводск' },
  { id: 'syktyvkar', label: 'Сыктывкар' },
  { id: 'yoshkar-ola', label: 'Йошкар-Ола' },
  { id: 'saransk', label: 'Саранск' },
  { id: 'yakutsk', label: 'Якутск' },
  { id: 'vladikavkaz', label: 'Владикавказ' },
  { id: 'kazan', label: 'Казань' },
  { id: 'kyzyl', label: 'Кызыл' },
  { id: 'abakan', label: 'Абакан' },
  { id: 'grozny', label: 'Грозный' },
  { id: 'cheboksary', label: 'Чебоксары' },
  { id: 'barnaul', label: 'Барнаул' },
  { id: 'chita', label: 'Чита' },
  { id: 'petropavlovsk-kamchatsky', label: 'Петропавловск-Камчатский' },
  { id: 'krasnodar', label: 'Краснодар' },
  { id: 'krasnoyarsk', label: 'Красноярск' },
  { id: 'vladivostok', label: 'Владивосток' },
  { id: 'stavropol', label: 'Ставрополь' },
  { id: 'khabarovsk', label: 'Хабаровск' },
  { id: 'blagoveshchensk', label: 'Благовещенск' },
  { id: 'arkhangelsk', label: 'Архангельск' },
  { id: 'astrakhan', label: 'Астрахань' },
  { id: 'belgorod', label: 'Белгород' },
  { id: 'bryansk', label: 'Брянск' },
  { id: 'vladimir', label: 'Владимир' },
  { id: 'volgograd', label: 'Волгоград' },
  { id: 'vologda', label: 'Вологда' },
  { id: 'voronezh', label: 'Воронеж' },
  { id: 'ivanovo', label: 'Иваново' },
  { id: 'irkutsk', label: 'Иркутск' },
  { id: 'kaliningrad', label: 'Калининград' },
  { id: 'kaluga', label: 'Калуга' },
  { id: 'kemerovo', label: 'Кемерово' },
  { id: 'kirov', label: 'Киров' },
  { id: 'kostroma', label: 'Кострома' },
  { id: 'kurgan', label: 'Курган' },
  { id: 'kursk', label: 'Курск' },
  { id: 'lipetsk', label: 'Липецк' },
  { id: 'magadan', label: 'Магадан' },
  { id: 'murmansk', label: 'Мурманск' },
  { id: 'nizhny-novgorod', label: 'Нижний Новгород' },
  { id: 'novgorod', label: 'Великий Новгород' },
  { id: 'novosibirsk', label: 'Новосибирск' },
  { id: 'omsk', label: 'Омск' },
  { id: 'orenburg', label: 'Оренбург' },
  { id: 'oryol', label: 'Орёл' },
  { id: 'penza', label: 'Пенза' },
  { id: 'perm', label: 'Пермь' },
  { id: 'pskov', label: 'Псков' },
  { id: 'rostov-on-don', label: 'Ростов-на-Дону' },
  { id: 'ryazan', label: 'Рязань' },
  { id: 'samara', label: 'Самара' },
  { id: 'saratov', label: 'Саратов' },
  { id: 'yuzhno-sakhalinsk', label: 'Южно-Сахалинск' },
  { id: 'yekaterinburg', label: 'Екатеринбург' },
  { id: 'smolensk', label: 'Смоленск' },
  { id: 'tambov', label: 'Тамбов' },
  { id: 'tver', label: 'Тверь' },
  { id: 'tomsk', label: 'Томск' },
  { id: 'tula', label: 'Тула' },
  { id: 'tyumen', label: 'Тюмень' },
  { id: 'ulyanovsk', label: 'Ульяновск' },
  { id: 'chelyabinsk', label: 'Челябинск' },
  { id: 'yaroslavl', label: 'Ярославль' },
  { id: 'naryan-mar', label: 'Нарьян-Мар' },
  { id: 'khanty-mansiysk', label: 'Ханты-Мансийск' },
  { id: 'anadyr', label: 'Анадырь' },
  { id: 'salekhard', label: 'Салехард' },
  { id: 'birobidzhan', label: 'Биробиджан' },
  { id: 'donetsk', label: 'Донецк' },
  { id: 'lugansk', label: 'Луганск' },
  { id: 'kherson', label: 'Херсон' },
  { id: 'zaporozhye', label: 'Запорожье' },
  { id: 'melitopol', label: 'Мелитополь' },
  { id: 'nazran', label: 'Назрань' },
  { id: 'maykop', label: 'Майкоп (Адыгея)' },
  { id: 'krasnogorsk', label: 'Красногорск' },
  { id: 'podolsk', label: 'Подольск' },
  { id: 'sochi', label: 'Сочи' },
  { id: 'murmashi', label: 'Мурмаши' },
]
